### ISSUE TITLE
Durability detection not working

### ISSUE THREAD

**Issue by leprucon** [MrTroot/autofish#12]
Not sure why, it simply isn't working.

**Comment by leprucon** [comment]
also, another issue that may or may not be due to this mod, but it rightclicks my fishing rod periodically whenever I have it out, regardless of whether it's off or in front of water. (may not be due to this mod, thought I have no idea what else could be causing it)

**Comment by leprucon** [comment]
it seems it was this mod causing the issue. after I undownloaded the right clicking stopped. I'll still use this mod, but I'll have to redownload and restart my game every time I use it

**Comment by troyhayes** [comment]
I've not been able to replicate this behavior. If this is still an issue, provide the game version and mod version, or other instructions to replicate.
