### ISSUE TITLE
Error loading autofish - cloth config

### ISSUE THREAD

**Issue by khartmansjsu** [MrTroot/autofish#21]
I'll try to be as descriptive as possible.

Following the instructions [here](https://www.curseforge.com/minecraft/mc-mods/autofish), I placed cloth-config-6.1.48-forge.jar and autofish-0.9.0-forge-mc1.16.1.jar in my mods folder.

After launching from my forge profile, I am met with the following error screen:
![image](https://user-images.githubusercontent.com/32494415/153060486-f88fa1a6-734d-468a-9549-551783b64643.png)

Of course, I have cloth-config in my mods folder (see below), so I do not understand what is happening. Please advise :)
I'll include the crash report and latest.log files in this issue.
![image](https://user-images.githubusercontent.com/32494415/153060780-146c0be1-39de-4eac-8e36-d859cdbc5aa7.png)

Crash report:
[crash-2022-02-08_13.16.18-fml.txt](https://github.com/MrTroot/autofish/files/8026838/crash-2022-02-08_13.16.18-fml.txt)
latest log:
[latest.log](https://github.com/MrTroot/autofish/files/8026844/latest.log)

**Comment by khartmansjsu** [comment]
Additional details: This error has persisted for various autofish and cloth-config version combinations. I don't see a duplicate of this issue on this repo or on the [cloth-config repo](https://github.com/shedaniel/cloth-config/issues?q=is%3Aissue).

**Comment by troyhayes** [comment]
For MC 1.16.1, the Cloth Config version I tested with is 4.0.2.
