### ISSUE TITLE
Wandering trader doesn't spawn while fishing

### ISSUE THREAD

**Issue by LukasFun** [MrTroot/autofish#25]
Fishing for about 30 hours with no trader spawning. The chance of that happening should be about 0.09%.

**Comment by WhitrayHB** [comment]
Are you sure there's no wandering trader spawn?Maybe you missed them. And maybe your AFK point doesn't have the condition to let them spawn. Or you are just unlucky lol.

**Comment by troyhayes** [comment]
Autofish has no interaction with entity spawning whatsoever.
