### ISSUE TITLE
I might have enabled debug so how do I disable it?

### ISSUE THREAD

**Issue by Sovietsupporter69** [MrTroot/autofish#37]
I keep getting chat messages like "fishing get Carrot: * 20" and "fishing get String: * 2", it only started recently and is spamming my chat so I want to fix it. I assume it is for this mod cause of the "fishing" but if it isn't then sorry for this.
![2022-10-14_22 02 37](https://user-images.githubusercontent.com/84580170/195943511-a90723de-f21a-42fc-831c-5a7babc0e230.png)

**Comment by Sovietsupporter69** [comment]
An update, I got the "fishing get Gunpowder: * 2" message and then the debug print stopped, but only for a while as it continued after about 4 mins of nothing, so I'm more unsure what caused it to start.

**Comment by troyhayes** [comment]
This mod does not have any such feature.
