### ISSUE TITLE
0.9.5-SNAPSHOT crashes game on 1.19.3

### ISSUE THREAD

**Issue by datsme** [MrTroot/autofish#42]
As the title says :)

**Comment by liblaf** [comment]
Try this PR #40, it works well for me on 1.19.3.
If you don't want to compile the project, you can try my build [here](https://drive.liblaf.top/github/autofish/).

**Comment by datsme** [comment]
Your build is working for me thanks (was faster than compiling it lol)

**Comment by AbdiAbdiAbdi** [comment]
it worked for me too! thank you!
