### ISSUE TITLE
Crashed in 1.19.2 (Java edition)

### ISSUE THREAD

**Issue by Penguin617** [MrTroot/autofish#44]
[crash-2022-12-29_21.27.52-client.txt](https://github.com/MrTroot/autofish/files/10320350/crash-2022-12-29_21.27.52-client.txt)

Not sure why it crashed, but pls help me in this anyway possible. Thank you in advance

**Comment by CheesyWeezy303** [comment]
Have you been able to fix this? I haven't.

**Comment by troyhayes** [comment]
Duplicate of #33 (closed)
