### ISSUE TITLE
pls add version 1.19.3

### ISSUE THREAD

**Issue by CraftBlack** [MrTroot/autofish#45]
pls add version 1.19.3

**Comment by PRRB** [comment]
I don't really know anything about java or MC mods and what process they get published to CurseForge so apologies in advance if I say something stupid.

Anyways - autofish appears in CurseForge if you create a new profile for 1.19 - however you cannot find it if you search for it in a profile targetting 1.19.1 or 1.19.2 even though the latest version works on those versions of MC if you add it manually to your mods folder.

Also the jar attached in comments to #40 should work for you on 1.19.3 - the repo owner has merged those changes into the main branch now too. I still don't see the mod showing up in CurseForge for 1.19.3 though, I wonder if it takes some time for the new version to get published though?

Either that, or maybe there is some manifest change or something like that needed to enable publishing the mod for MC minor versions via curseforge?

**Comment by troyhayes** [comment]
It's on CurseForge now. I upload the compiled jar manually. They take a bit of time to approve the upload before it becomes available to download.
