### ISSUE TITLE
It does not work.

### ISSUE THREAD

**Issue by mouel466** [MrTroot/autofish#47]
I downloaded the latest fabric mod tried it and the rod does nothing when a fish is caught. I can change the settings which mean the mods is running but it does not catch anything.

I'm playing on fabric-loader-0.14.13-1.19.9

**Comment by PRRB** [comment]
`I'm playing on fabric-loader-0.14.13-1.19.9`
I think you mean fabric-loader-0.14.13-1.19.3?

It is working fine for me with the default settings.
![javaw_2023-02-05_13-44-13](https://user-images.githubusercontent.com/33292978/216823014-dc6c6af9-5589-4dd1-b33a-3fdd1bc51bae.png)
![javaw_2023-02-05_13-43-59](https://user-images.githubusercontent.com/33292978/216823016-306e4ff5-d828-4e05-bd40-976d13e3682e.png)
![javaw_2023-02-05_13-45-16](https://user-images.githubusercontent.com/33292978/216823018-8e63a03a-d2e3-48b3-8d56-3f14d76116d7.png)

**Comment by mouel466** [comment]
> `I'm playing on fabric-loader-0.14.13-1.19.9` I think you mean fabric-loader-0.14.13-1.19.3?
> 
> It is working fine for me with the default settings. ![javaw_2023-02-05_13-44-13](https://user-images.githubusercontent.com/33292978/216823014-dc6c6af9-5589-4dd1-b33a-3fdd1bc51bae.png) ![javaw_2023-02-05_13-43-59](https://user-images.githubusercontent.com/33292978/216823016-306e4ff5-d828-4e05-bd40-976d13e3682e.png) ![javaw_2023-02-05_13-45-16](https://user-images.githubusercontent.com/33292978/216823018-8e63a03a-d2e3-48b3-8d56-3f14d76116d7.png)

I forgot about this, I will try it again and see.
