### ISSUE TITLE
Game Crashes when using the mod.

### ISSUE THREAD

**Issue by graven04** [MrTroot/autofish#49]
When using the mod by just fishing it refuses to catch anything at all. When you attempt to use the menu by pressing "V" it just crashes. I am currently using the latest mod for 1.19.3. Ive had a look at issue #33 but even using that jar it is the same. I even tried removing dynamic fps but it still does the same behavior.

**Comment by hydrix9** [comment]
needs to be updated to 1.19.4

https://github.com/MrTroot/autofish/pull/48

does this I believe, I stupidly did the same changes independently and confirm its working

**Comment by graven04** [comment]
But I am using 1.19.3

**Comment by hydrix9** [comment]
alright np upload the crash report if you can

**Comment by graven04** [comment]
https://pastebin.com/1jecNq1n

sometimes it starts working, but when it does not work it does not auto reel and when trying to open the menu it crashes.

**Comment by hydrix9** [comment]
looks like you're using Cloth Config 8.2.88, please use this 
[9.0.94](https://www.curseforge.com/minecraft/mc-mods/cloth-config/files/4147098)
that is Cloth Config version 9.0.94, it's the one meant for 1.19.3

version lists for cloth config here
https://www.curseforge.com/minecraft/mc-mods/cloth-config/files

**Comment by graven04** [comment]
worked, thanks
