### ISSUE TITLE
[Suggestion] Add like particle detector?

### ISSUE THREAD

**Issue by barraIhsan** [MrTroot/autofish#6]
So in [this](https://youtu.be/1A8hG-b_sCo) video, its explained the mechanics of fishing (yeah i know, its very old video, but I think its still work that way)
So when you doesn't see x particle in x gametick, then you should be recast because its just make the fishing even longer? So please add that feature

**Comment by troyhayes** [comment]
That's a super interesting video. But it goes beyond both my expertise and the scope of this mod.
